version: "3.9"

x-common-logging: &logging
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "3"

services:
  # ── Execution client ───────────────────────────────────────────────
  geth:
    image: ethereum/client-go:stable
    container_name: geth
    <<: *logging
    command:
      - "--syncmode=snap"
      - "--datadir=/geth"
      - "--port=30303"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=eth,net,web3,txpool"
      - "--http.corsdomain=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.port=8546"
      - "--graphql"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.vhosts=*"
      - "--authrpc.jwtsecret=/secrets/jwt.hex"
      - "--metrics"
      - "--metrics.addr=0.0.0.0"
      - "--metrics.port=6060"
      - "--verbosity=3"
      - "--maxpeers=100"
      - "--nat=extip:116.255.44.11"
      # ── alternatively, you can uncomment to disable Geth’s NAT logic entirely ──
      # - "--nat=none"
      # ── Use official Ethereum mainnet bootnodes ──
    volumes:
      - geth-data:/geth
      - ./jwtsecret:/secrets:ro
    ports:
      - "8545:8545/tcp"
      - "8546:8546/tcp"
      - "8551:8551/tcp"
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/udp"
      - "6060:6060/tcp"
    networks:
      - ethereum-network

  # ── Consensus client ───────────────────────────────────────────────
  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    <<: *logging
    depends_on: [geth]
    command:
      - "lighthouse"
      - "bn"
      - "--network=mainnet"
      - "--execution-endpoint=http://geth:8551"
      - "--execution-jwt=/secrets/jwt.hex"
      - "--checkpoint-sync-url=https://beaconstate.ethstaker.cc"
      - "--datadir=/lighthouse"
      - "--listen-address=0.0.0.0"
      - "--listen-address=::"
      - "--http"
      - "--http-address=0.0.0.0"
      - "--http-port=5052"
      - "--port=9000"
      - "--metrics"
    volumes:
      - lighthouse-data:/lighthouse
      - ./jwtsecret:/secrets:ro
    ports:
      - "5052:5052/tcp"
      - "5054:5054/tcp"
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "9001:9001/udp"
    networks:
      - ethereum-network

volumes:
  geth-data:
  lighthouse-data:

networks:
  ethereum-network:
    driver: bridge
